# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Covid19(object):
    def setupUi(self, Covid19):
        Covid19.setObjectName("Covid19")
        Covid19.resize(994, 766)
        self.centralwidget = QtWidgets.QWidget(Covid19)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setObjectName("Tab")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BG_slider = QtWidgets.QSlider(self.tab_1)
        self.BG_slider.setOrientation(QtCore.Qt.Horizontal)
        self.BG_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.BG_slider.setTickInterval(1)
        self.BG_slider.setObjectName("BG_slider")
        self.horizontalLayout_3.addWidget(self.BG_slider)
        self.BG_slider_label = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.BG_slider_label.setFont(font)
        self.BG_slider_label.setObjectName("BG_slider_label")
        self.horizontalLayout_3.addWidget(self.BG_slider_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.BG_export_button = QtWidgets.QPushButton(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BG_export_button.setFont(font)
        self.BG_export_button.setObjectName("BG_export_button")
        self.gridLayout_2.addWidget(self.BG_export_button, 3, 1, 1, 1)
        self.covid19_1st_label = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.covid19_1st_label.setFont(font)
        self.covid19_1st_label.setAlignment(QtCore.Qt.AlignCenter)
        self.covid19_1st_label.setObjectName("covid19_1st_label")
        self.gridLayout_2.addWidget(self.covid19_1st_label, 0, 0, 1, 2)
        self.BG_plotWidget = PlotWidget(self.tab_1)
        self.BG_plotWidget.setObjectName("BG_plotWidget")
        self.gridLayout_2.addWidget(self.BG_plotWidget, 4, 0, 1, 2)
        self.BG_resume_button = QtWidgets.QPushButton(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BG_resume_button.setFont(font)
        self.BG_resume_button.setObjectName("BG_resume_button")
        self.gridLayout_2.addWidget(self.BG_resume_button, 3, 0, 1, 1)
        self.BG_label = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BG_label.setFont(font)
        self.BG_label.setObjectName("BG_label")
        self.gridLayout_2.addWidget(self.BG_label, 1, 0, 1, 1)
        self.Tab.addTab(self.tab_1, "")
        self.gridLayout_4.addWidget(self.Tab, 0, 0, 1, 1)
        Covid19.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Covid19)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 26))
        self.menubar.setObjectName("menubar")
        Covid19.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Covid19)
        self.statusbar.setObjectName("statusbar")
        Covid19.setStatusBar(self.statusbar)

        self.retranslateUi(Covid19)
        self.Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Covid19)

    def retranslateUi(self, Covid19):
        _translate = QtCore.QCoreApplication.translate
        Covid19.setWindowTitle(_translate("Covid19", "MainWindow"))
        self.BG_slider_label.setText(_translate("Covid19", "Observation Date"))
        self.BG_export_button.setText(_translate("Covid19", "Export"))
        self.covid19_1st_label.setText(_translate("Covid19", "Covid-19 Data Visualization"))
        self.BG_resume_button.setText(_translate("Covid19", "Stop/Resume"))
        self.BG_label.setText(_translate("Covid19", "Bubble Graph"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_1), _translate("Covid19", "Bubble"))

from pyqtgraph import PlotWidget
