# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SongSplitter.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1865, 1500)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(0, 0, 55, 255), stop:1 rgba(55, 60, 127, 255));\n"
"border-color: transparent;;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setStyleSheet("background-color: transparent;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Import = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Import.setFont(font)
        self.Import.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Import.setObjectName("Import")
        self.horizontalLayout.addWidget(self.Import)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Original_GV = PlotWidget(self.frame_5)
        self.Original_GV.setMinimumSize(QtCore.QSize(0, 375))
        self.Original_GV.setObjectName("Original_GV")
        self.gridLayout_3.addWidget(self.Original_GV, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Play_original = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Play_original.setFont(font)
        self.Play_original.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Play_original.setObjectName("Play_original")
        self.verticalLayout_4.addWidget(self.Play_original)
        self.Stop = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Stop.setFont(font)
        self.Stop.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Stop.setObjectName("Stop")
        self.verticalLayout_4.addWidget(self.Stop)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setStyleSheet("background-color: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.Music_GV = PlotWidget(self.frame_4)
        self.Music_GV.setMinimumSize(QtCore.QSize(0, 375))
        self.Music_GV.setObjectName("Music_GV")
        self.gridLayout.addWidget(self.Music_GV, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Play_Music = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Play_Music.setFont(font)
        self.Play_Music.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Play_Music.setObjectName("Play_Music")
        self.verticalLayout_2.addWidget(self.Play_Music)
        self.Stop2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Stop2.setFont(font)
        self.Stop2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Stop2.setObjectName("Stop2")
        self.verticalLayout_2.addWidget(self.Stop2)
        self.Save_music = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Save_music.setFont(font)
        self.Save_music.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Save_music.setObjectName("Save_music")
        self.verticalLayout_2.addWidget(self.Save_music)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.Vocals_GV = PlotWidget(self.frame_4)
        self.Vocals_GV.setMinimumSize(QtCore.QSize(0, 375))
        self.Vocals_GV.setObjectName("Vocals_GV")
        self.gridLayout.addWidget(self.Vocals_GV, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Play_vocals = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Play_vocals.setFont(font)
        self.Play_vocals.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Play_vocals.setObjectName("Play_vocals")
        self.verticalLayout_3.addWidget(self.Play_vocals)
        self.Stop3 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Stop3.setFont(font)
        self.Stop3.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Stop3.setObjectName("Stop3")
        self.verticalLayout_3.addWidget(self.Stop3)
        self.Save_vocals = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Save_vocals.setFont(font)
        self.Save_vocals.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Save_vocals.setObjectName("Save_vocals")
        self.verticalLayout_3.addWidget(self.Save_vocals)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setStyleSheet("background-color: transparent;\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Import_ECG = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Import_ECG.setFont(font)
        self.Import_ECG.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.992284, y1:0.5, x2:1, y2:0, stop:0.588535 rgba(180, 213, 255, 255), stop:0.979098 rgba(72, 150, 202, 255));")
        self.Import_ECG.setObjectName("Import_ECG")
        self.horizontalLayout_3.addWidget(self.Import_ECG)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.frame_12 = QtWidgets.QFrame(self.tab_4)
        self.frame_12.setStyleSheet("background-color: transparent;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Original_ECG = PlotWidget(self.frame_12)
        self.Original_ECG.setMinimumSize(QtCore.QSize(0, 375))
        self.Original_ECG.setObjectName("Original_ECG")
        self.gridLayout_6.addWidget(self.Original_ECG, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setStyleSheet("background-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ECG = PlotWidget(self.frame_6)
        self.ECG.setMinimumSize(QtCore.QSize(0, 375))
        self.ECG.setObjectName("ECG")
        self.gridLayout_5.addWidget(self.ECG, 0, 0, 1, 1)
        self.Arrhythmia = PlotWidget(self.frame_6)
        self.Arrhythmia.setMinimumSize(QtCore.QSize(0, 375))
        self.Arrhythmia.setObjectName("Arrhythmia")
        self.gridLayout_5.addWidget(self.Arrhythmia, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1865, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose stereo *.wav song"))
        self.Import.setText(_translate("MainWindow", "Import"))
        self.Play_original.setText(_translate("MainWindow", "play"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Play_Music.setText(_translate("MainWindow", "play"))
        self.Stop2.setText(_translate("MainWindow", "Stop"))
        self.Save_music.setText(_translate("MainWindow", "Save"))
        self.Play_vocals.setText(_translate("MainWindow", "play"))
        self.Stop3.setText(_translate("MainWindow", "Stop"))
        self.Save_vocals.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Music-Voclas separation"))
        self.label_3.setText(_translate("MainWindow", "Choose *.CSV File"))
        self.Import_ECG.setText(_translate("MainWindow", "Import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "ECG-arrhythmia separation"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
