# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'piano.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(145, 145, 145);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 590))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.Piano1 = QtWidgets.QPushButton(self.frame)
        self.Piano1.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Piano1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano1.setObjectName("Piano1")
        self.gridLayout.addWidget(self.Piano1, 0, 0, 3, 1)
        self.Piano2 = QtWidgets.QPushButton(self.frame)
        self.Piano2.setMinimumSize(QtCore.QSize(0, 400))
        self.Piano2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Piano2.setText("")
        self.Piano2.setObjectName("Piano2")
        self.gridLayout.addWidget(self.Piano2, 0, 1, 1, 1)
        self.Piano3 = QtWidgets.QPushButton(self.frame)
        self.Piano3.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano3.setObjectName("Piano3")
        self.gridLayout.addWidget(self.Piano3, 0, 2, 3, 1)
        self.Piano4 = QtWidgets.QPushButton(self.frame)
        self.Piano4.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano4.setObjectName("Piano4")
        self.gridLayout.addWidget(self.Piano4, 0, 3, 3, 1)
        self.Piano5 = QtWidgets.QPushButton(self.frame)
        self.Piano5.setMinimumSize(QtCore.QSize(0, 400))
        self.Piano5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Piano5.setText("")
        self.Piano5.setObjectName("Piano5")
        self.gridLayout.addWidget(self.Piano5, 0, 4, 2, 1)
        self.Piano6 = QtWidgets.QPushButton(self.frame)
        self.Piano6.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano6.setObjectName("Piano6")
        self.gridLayout.addWidget(self.Piano6, 0, 5, 3, 1)
        self.Piano7 = QtWidgets.QPushButton(self.frame)
        self.Piano7.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano7.setObjectName("Piano7")
        self.gridLayout.addWidget(self.Piano7, 0, 6, 3, 1)
        self.Piano8 = QtWidgets.QPushButton(self.frame)
        self.Piano8.setMinimumSize(QtCore.QSize(0, 400))
        self.Piano8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Piano8.setText("")
        self.Piano8.setObjectName("Piano8")
        self.gridLayout.addWidget(self.Piano8, 0, 7, 2, 1)
        self.Piano9 = QtWidgets.QPushButton(self.frame)
        self.Piano9.setMinimumSize(QtCore.QSize(0, 750))
        self.Piano9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piano9.setObjectName("Piano9")
        self.gridLayout.addWidget(self.Piano9, 0, 8, 3, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 400))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 1, 2, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 400))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 400))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xylophone1 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone1.setMinimumSize(QtCore.QSize(0, 700))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone1.setFont(font)
        self.Xylophone1.setStyleSheet("background-color: rgb(203, 0, 0);")
        self.Xylophone1.setText("")
        self.Xylophone1.setObjectName("Xylophone1")
        self.horizontalLayout.addWidget(self.Xylophone1)
        self.Xylophone2 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone2.setMinimumSize(QtCore.QSize(0, 660))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone2.setFont(font)
        self.Xylophone2.setStyleSheet("background-color: rgb(226, 151, 0);")
        self.Xylophone2.setText("")
        self.Xylophone2.setObjectName("Xylophone2")
        self.horizontalLayout.addWidget(self.Xylophone2)
        self.Xylophone3 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone3.setMinimumSize(QtCore.QSize(0, 620))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone3.setFont(font)
        self.Xylophone3.setStyleSheet("background-color: rgb(245, 245, 0);")
        self.Xylophone3.setText("")
        self.Xylophone3.setObjectName("Xylophone3")
        self.horizontalLayout.addWidget(self.Xylophone3)
        self.Xylophone4 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone4.setMinimumSize(QtCore.QSize(0, 580))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone4.setFont(font)
        self.Xylophone4.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.Xylophone4.setText("")
        self.Xylophone4.setObjectName("Xylophone4")
        self.horizontalLayout.addWidget(self.Xylophone4)
        self.Xylophone5 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone5.setMinimumSize(QtCore.QSize(0, 540))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone5.setFont(font)
        self.Xylophone5.setStyleSheet("background-color: rgb(0, 241, 241);")
        self.Xylophone5.setText("")
        self.Xylophone5.setObjectName("Xylophone5")
        self.horizontalLayout.addWidget(self.Xylophone5)
        self.Xylophone6 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone6.setMinimumSize(QtCore.QSize(0, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone6.setFont(font)
        self.Xylophone6.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.Xylophone6.setText("")
        self.Xylophone6.setObjectName("Xylophone6")
        self.horizontalLayout.addWidget(self.Xylophone6)
        self.Xylophone7 = QtWidgets.QPushButton(self.tab_2)
        self.Xylophone7.setMinimumSize(QtCore.QSize(0, 460))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Xylophone7.setFont(font)
        self.Xylophone7.setStyleSheet("background-color: rgb(148, 0, 222);")
        self.Xylophone7.setText("")
        self.Xylophone7.setObjectName("Xylophone7")
        self.horizontalLayout.addWidget(self.Xylophone7)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Piano1.setText(_translate("MainWindow", "A"))
        self.Piano3.setText(_translate("MainWindow", "B"))
        self.Piano4.setText(_translate("MainWindow", "C"))
        self.Piano6.setText(_translate("MainWindow", "D"))
        self.Piano7.setText(_translate("MainWindow", "E"))
        self.Piano9.setText(_translate("MainWindow", "F"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Piano"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Xylophone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

